#!/usr/bin/env python3
"""Bring the Observability Stack up from a clean checkout, or refuse with a reason.

Lock the env file, fill in
missing secrets, refuse to invent secrets over existing data, create the shared platform
network, start the stack, wait for readiness, print the next step. Exit codes: 0 ready,
1 refused (the JSON line on stderr names why), 2 bad usage, 3 the stack did not become
ready. Python 3.11+ standard library only.
"""

from __future__ import annotations

import argparse
import fcntl
import json
import http.client
import ipaddress
import socket
import ssl
import os
import re
import secrets
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
import urllib.parse
from datetime import datetime, timezone
from functools import partial
from pathlib import Path
from typing import Callable

from status_io import Unavailable, now, task_record

PROJECT = "observability-stack"
NETWORK = "platform"
VOLUMES = ("caddy-data", "caddy-config", "grafana-data", "alloy-data",
           "loki-data", "tempo-data", "mimir-data", "rustfs-data")

# Secrets the stack needs and how many random bytes each gets (hex encoded).
SECRETS: dict[str, int] = {
    "OB_GRAFANA_ADMIN_PASSWORD": 24,
    "OB_S3_ACCESS_KEY": 10,
    "OB_S3_SECRET_KEY": 24,
}
MANAGED = set(SECRETS)
IMAGE_LINE = re.compile(r"^\s+image:\s+(?P<ref>\S+)\s*$")
ENV_LINE = re.compile(r"^(?:export\s+)?(?P<key>[A-Z][A-Z0-9_]*)=(?P<value>.*)$")


class Refused(Exception):
    def __init__(self, code: str, detail: str = "") -> None:
        super().__init__(code)
        self.code = code
        self.detail = detail


Runner = Callable[..., subprocess.CompletedProcess[str]]


def run(argv: list[str], *, timeout: float | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(argv, text=True, capture_output=True, check=False, timeout=timeout)


def read_env(path: Path) -> tuple[list[str], dict[str, str]]:
    """Return the raw lines and the managed assignments. Unmanaged lines are kept verbatim."""
    if not path.exists():
        return [], {}
    lines = path.read_text(encoding="utf-8").splitlines()
    values: dict[str, str] = {}
    for line in lines:
        match = ENV_LINE.match(line)
        if not match:
            continue
        key, value = match.group("key"), match.group("value")
        if key in MANAGED:
            if key in values:
                raise Refused("env_repair_required", f"{key} is set twice in {path}")
            if not value or value.startswith(("'", '"')) or "${" in value:
                raise Refused("env_repair_required", f"{key} must be a plain value in {path}")
            values[key] = value
    return lines, values


def generate(missing: set[str]) -> dict[str, str]:
    fresh: dict[str, str] = {}
    for key in sorted(missing):
        fresh[key] = secrets.token_hex(SECRETS[key])
    return fresh


def write_env(path: Path, lines: list[str], template: Path, fresh: dict[str, str]) -> None:
    if not lines:
        lines = template.read_text(encoding="utf-8").splitlines()
        lines += ["", "# Generated by scripts/bootstrap.py. Keep this file private and backed up."]
    lines += [f"{key}={value}" for key, value in fresh.items()]
    tmp = path.with_name(path.name + ".tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    os.replace(tmp, path)
    os.chmod(path, 0o600)


def unquote(value: str) -> str:
    """Compose accepts 'x' and "x"; a bare value is used as is."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def project_name(settings: dict[str, str]) -> str:
    """Same precedence as Compose: shell environment, then the env file, then name:."""
    return os.environ.get("COMPOSE_PROJECT_NAME") or unquote(settings.get("COMPOSE_PROJECT_NAME", "")) or PROJECT


def installation_state(root: Path, data_dir: Path, runner: Runner, project: str = PROJECT, prefix: str | None = None) -> list[str]:
    """Every place an earlier installation of this project could have left data."""
    found: list[str] = []
    prefixes = (f"{project}_", f"{prefix or project}_")
    if data_dir.exists():
        if not os.access(data_dir, os.R_OK | os.X_OK):
            raise Refused("data_dir_unreadable", str(data_dir))
        if any(data_dir.iterdir()):
            found.append(f"data at {data_dir}")
    result = runner(["docker", "volume", "ls", "--format", "{{.Name}}"])
    if result.returncode != 0:
        raise Refused("docker_unavailable", result.stderr.strip())
    names = {name for name in result.stdout.split() if name.startswith(prefixes)}
    labelled = runner(["docker", "volume", "ls", "--filter",
                       f"label=com.docker.compose.project={project}", "--format", "{{.Name}}"])
    if labelled.returncode != 0:
        raise Refused("docker_unavailable", labelled.stderr.strip())
    for name in sorted(names | set(labelled.stdout.split())):
        found.append(f"volume {name}")
    return found


def images(compose: Path) -> dict[str, str]:
    """Shipped service references only; ignores env files and the shell."""
    out: dict[str, str] = {}
    service = ""
    for line in compose.read_text(encoding="utf-8").splitlines():
        head = re.match(r"^  (?P<name>[a-z][a-z0-9-]*):\s*$", line)
        if head:
            service = head.group("name")
        match = IMAGE_LINE.match(line)
        if match and service:
            ref = match.group("ref")
            fallback = re.fullmatch(r"\$\{OB_[A-Z0-9_]+_IMAGE:-(.+)\}", ref)
            out[service] = fallback[1] if fallback else ref
            if '${' in out[service]:
                raise Refused('image_default_unrecognized', service)
    return out


def write_versions(root: Path, compose: Path, settings: dict[str, str] | None = None, *, services: dict) -> None:
    state = Path((settings or {}).get("OB_STATE_DIR", str(root / "data")))
    console = (state if state.is_absolute() else root / state) / "console"
    console.mkdir(mode=0o755, parents=True, exist_ok=True)
    tags = {}
    for service in images(compose):
        ref = services.get(service, {}).get("image", "")
        # Publish only version labels from valid references, never the resolved environment.
        if not re.fullmatch(r"[a-z0-9][a-z0-9./:_-]*(?:@[a-z0-9]+:[0-9a-f]+)?", ref, re.I):
            tags[service] = "unknown"
        else:
            name, _, digest = ref.partition("@")
            leaf = name.rsplit("/", 1)[-1]
            tags[service] = leaf.split(":", 1)[1] if ":" in leaf else (digest or "latest")
    doc = {
        "pinnedAt": datetime.fromtimestamp(compose.stat().st_mtime, timezone.utc).isoformat(),
        "configuredAt": datetime.now(timezone.utc).isoformat(),
        "images": tags,
        "links": {
            "gateway": (settings or {}).get("OB_GATEWAY_URL", ""),
            "backplane": (settings or {}).get("OB_BACKPLANE_URL", ""),
        },
    }
    (console / "versions.json").write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    settings = settings or {}
    links = {"grafana": grafana_origin(settings)}
    links.update({key: value for key, value in doc["links"].items() if value})
    if settings.get("OB_RUSTFS_CONSOLE") == "true":
        links["rustfs"] = rustfs_origin(settings)
    (console / "links.json").write_text(json.dumps(links) + "\n", encoding="utf-8")


def ensure_network(runner: Runner, name: str = NETWORK) -> None:
    probe = runner(["docker", "network", "inspect", name])
    if probe.returncode == 0:
        return
    created = runner(["docker", "network", "create", name])
    if created.returncode != 0:
        raise Refused("network_create_failed", created.stderr.strip())


def ensure_volumes(runner: Runner, prefix: str, project: str, s3: bool = False) -> None:
    for key in VOLUMES:
        if key == "rustfs-data" and not s3:
            continue
        name = f"{prefix}_{key}"
        result = runner(["docker", "volume", "create", "--label",
                         f"com.docker.compose.project={project}", name])
        if result.returncode:
            raise Refused("volume_create_failed", name)


def alert_config(settings: dict[str, str]) -> tuple[str, dict[str, str]]:
    if settings.get("OB_ALERT_WEBHOOK_URL"):
        url = urllib.parse.urlsplit(settings["OB_ALERT_WEBHOOK_URL"])
        if url.scheme not in ("http", "https") or not url.hostname:
            raise Refused("alert_delivery_invalid", "OB_ALERT_WEBHOOK_URL must be an HTTP(S) URL")
        return "webhook", {}
    if settings.get("OB_ALERT_EMAIL") and not settings["OB_ALERT_EMAIL"].endswith("@example.invalid") and settings.get("OB_SMTP_URL"):
        url = urllib.parse.urlsplit(settings["OB_SMTP_URL"])
        if url.scheme not in ("smtp", "smtps") or not url.hostname:
            raise Refused("alert_delivery_invalid", "OB_SMTP_URL must be smtp[s]://[user:password@]host:port")
        try:
            port = url.port or (465 if url.scheme == "smtps" else 587)
        except ValueError as error:
            raise Refused("alert_delivery_invalid", "invalid SMTP port") from error
        host = f"[{url.hostname}]" if ":" in url.hostname else url.hostname
        smtp = {
            "enabled": "true", "host": f"{host}:{port}",
            "user": urllib.parse.unquote(url.username or ""),
            "password": urllib.parse.unquote(url.password or ""),
            "from_address": settings["OB_ALERT_EMAIL"],
            "startTLS_policy": "MandatoryStartTLS" if url.scheme == "smtp" else "NoStartTLS",
        }
        for value in smtp.values():
            if any(c in value for c in ('\n', '\r', '"""')):
                raise Refused("alert_delivery_invalid", "SMTP values must be single-line without triple quotes")
        return "email", smtp
    if settings.get("OB_ALERTS") == "placeholder":
        return "placeholder", {}
    raise Refused("alert_delivery_required", "set OB_ALERT_WEBHOOK_URL or OB_ALERT_EMAIL and OB_SMTP_URL; "
                  "OB_ALERTS=placeholder explicitly permits degraded delivery")


def write_provisioning(root: Path, state: Path, settings: dict[str, str]) -> str:
    kind, smtp = alert_config(settings)
    state.mkdir(mode=0o700, parents=True, exist_ok=True)
    os.chmod(state, 0o700)
    provisioning = state / "grafana-provisioning"
    shutil.copytree(root / "docker/grafana/provisioning", provisioning, dirs_exist_ok=True)
    contact = {"apiVersion": 1, "contactPoints": [{"orgId": 1, "name": "configure-delivery",
               "receivers": [{"uid": "configure-delivery", "type": "email" if kind == "placeholder" else kind,
                              "disableResolveMessage": False, "settings":
                              {"url": "$OB_ALERT_WEBHOOK_URL"} if kind == "webhook" else
                              {"addresses": "$OB_ALERT_EMAIL" if kind == "email" else "configure@example.invalid"}}]}],
               "policies": [{"orgId": 1, "receiver": "configure-delivery", "group_by": ["grafana_folder", "alertname"]}]}
    (provisioning / "alerting/contact-points.yaml").write_text(json.dumps(contact, indent=2) + "\n")
    (state / "grafana.ini").write_text("[smtp]\n" + "".join(f'{key} = """{value}"""\n' for key, value in smtp.items()))
    os.chmod(state / "grafana.ini", 0o644)
    console = state / "console"
    console.mkdir(mode=0o755, parents=True, exist_ok=True)
    marker = console / "alerts-degraded.json"
    if kind == "placeholder":
        marker.write_text('{"status":"degraded","problem":"alert_delivery_placeholder"}\n')
    else:
        marker.unlink(missing_ok=True)
    return kind


def local_origin(settings: dict[str, str], scheme: str | None = None) -> str:
    scheme = scheme or ("https" if settings.get("OB_ACCESS_MODE") == "public" else "http")
    port = settings.get("OB_HTTPS_PORT" if scheme == "https" else "OB_HTTP_PORT") or ("443" if scheme == "https" else "80")
    return f"{scheme}://127.0.0.1:{port}"


def grafana_origin(settings: dict[str, str]) -> str:
    return settings.get("OB_GRAFANA_URL") or (
        f'{settings.get("OB_SCHEME", "http")}://'
        f'{settings.get("OB_GRAFANA_HOST", "grafana.localhost")}'
        f'{settings.get("OB_PUBLIC_PORT_SUFFIX", "")}')


def rustfs_origin(settings: dict[str, str]) -> str:
    return settings.get("OB_RUSTFS_URL") or (
        f'{settings.get("OB_SCHEME", "http")}://'
        f'{settings.get("OB_RUSTFS_HOST", "rustfs.localhost")}'
        f'{settings.get("OB_PUBLIC_PORT_SUFFIX", "")}')


def browser_url_config(settings: dict[str, str], app: str) -> None:
    prefix = "OB_" + app.upper()
    # Validate before urlsplit, which silently strips some whitespace characters.
    origin = settings.get(prefix + "_URL", "")
    settings[prefix + "_URL"] = origin
    settings[prefix + "_URL_HOST"] = ""
    settings[prefix + "_AUTHORITY"] = ""
    if not origin:
        return
    try:
        if re.search(r"[\s/?#@\\]", origin.removeprefix("https://").removeprefix("http://")):
            raise ValueError
        url = urllib.parse.urlsplit(origin)
        host = url.hostname or ""
        if url.scheme not in ("http", "https") or not url.netloc or url.path or url.query or url.fragment:
            raise ValueError
        if url.netloc.startswith("["):
            if not re.fullmatch(r"[0-9a-f:.]+", host):
                raise ValueError
            ipaddress.IPv6Address(host)
            authority_host = "[" + host + "]"
        else:
            if len(host) > 253 or not all(re.fullmatch(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?", label)
                                          for label in host.split(".")):
                raise ValueError
            authority_host = host
        port = url.port
        if port is not None and not 1 <= port <= 65535:
            raise ValueError
        authority = authority_host + (":" + str(port) if port is not None else "")
        if url.netloc.lower() != authority:
            raise ValueError
        if settings["OB_ACCESS_MODE"] == "public" and url.scheme != "https":
            raise ValueError
    except ValueError as error:
        raise Refused(app + "_url_invalid", prefix + "_URL must be an HTTP(S) origin with no path, "
                      "credentials, query or fragment; public mode requires HTTPS") from error
    if port == (443 if url.scheme == "https" else 80):
        authority = authority_host
    settings[prefix + "_URL"] = url.scheme + "://" + authority
    settings[prefix + "_URL_HOST"] = host
    settings[prefix + "_AUTHORITY"] = authority


def access_config(settings: dict[str, str]) -> None:
    mode = settings.get("OB_ACCESS_MODE") or "local"
    if mode not in ("local", "public", "proxy"):
        raise Refused("access_mode_invalid", "OB_ACCESS_MODE must be local, public or proxy")
    settings["OB_ACCESS_MODE"] = mode
    settings["OB_SCHEME"] = settings.get("OB_SCHEME") or ("http" if mode == "local" else "https")
    if (settings["OB_SCHEME"] not in ("http", "https") or
            (mode == "public" and settings["OB_SCHEME"] != "https")):
        raise Refused("access_mode_conflict", "OB_SCHEME must be http or https; public mode requires https")
    domain = settings.get("OB_PUBLIC_DOMAIN") or "localhost"
    settings["OB_PUBLIC_DOMAIN"] = domain
    try:
        ipaddress.ip_address(domain)
        ip_root = True
    except ValueError:
        ip_root = False
    settings["OB_GRAFANA_HOST"] = settings.get("OB_GRAFANA_HOST") or ("grafana.localhost" if ip_root else "grafana." + domain)
    settings["OB_RUSTFS_HOST"] = settings.get("OB_RUSTFS_HOST") or ("rustfs.localhost" if ip_root else "rustfs." + domain)
    # Disabled RustFS still reserves an HTTP site returning 404. Validate that host too.
    hosts = (domain, settings["OB_GRAFANA_HOST"], settings["OB_RUSTFS_HOST"])
    for host in hosts:
        if len(host) > 253 or any(not re.fullmatch(r"[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?", label)
               for label in host.split(".")):
            raise Refused("access_host_invalid", "root and application hosts must be explicit DNS names or an IPv4 root")
    if len(set(host.lower() for host in hosts)) != len(hosts):
        raise Refused("access_host_invalid", "applications require separate internal hostnames")
    if mode == "public":
        public_hosts = (domain, settings["OB_GRAFANA_HOST"])
        if settings.get("OB_RUSTFS_CONSOLE") == "true":
            public_hosts += (settings["OB_RUSTFS_HOST"],)
        for host in public_hosts:
            try:
                ipaddress.ip_address(host)
                public_ip = True
            except ValueError:
                public_ip = False
            if public_ip or "." not in host or host.endswith(".localhost"):
                raise Refused("access_host_invalid", "public mode requires public DNS hostnames")
    suffix = settings.get("OB_PUBLIC_PORT_SUFFIX", "")
    if suffix and (not re.fullmatch(r":[0-9]+", suffix) or not 1 <= int(suffix[1:]) <= 65535):
        raise Refused("access_port_invalid", "OB_PUBLIC_PORT_SUFFIX must be empty or :port")
    for key in ("OB_HTTP_PORT", "OB_HTTPS_PORT"):
        port = settings.get(key, "80" if key == "OB_HTTP_PORT" else "443")
        if not port.isdigit() or not 1 <= int(port) <= 65535:
            raise Refused("access_port_invalid", key + " must be a port number")
    browser_url_config(settings, "grafana")
    browser_url_config(settings, "rustfs")
    if (settings["OB_RUSTFS_URL_HOST"] == settings["OB_GRAFANA_HOST"].lower() or
            settings["OB_GRAFANA_URL_HOST"] == settings["OB_RUSTFS_HOST"].lower()):
        raise Refused("rustfs_origin_conflict", "browser origins must not reuse another application's internal hostname")
    enabled = settings.get("OB_RUSTFS_CONSOLE") or "false"
    if enabled not in ("true", "false"):
        raise Refused("rustfs_console_invalid", "OB_RUSTFS_CONSOLE must be true or false")
    settings["OB_RUSTFS_CONSOLE"] = enabled
    if enabled == "true" and "s3" not in settings.get("COMPOSE_PROFILES", "").split(","):
        raise Refused("rustfs_console_requires_s3", "enable the console only on an existing S3 installation; "
                      "storage changes require an explicit migration")
    # Proxy routing compares authorities; the scheme cannot distinguish routes.
    origins = (rustfs_origin(settings), grafana_origin(settings),
               settings["OB_SCHEME"] + "://" + domain + suffix)
    urls = [urllib.parse.urlsplit(origin) for origin in origins]
    authorities = [url.netloc.lower().removesuffix(":443" if url.scheme == "https" else ":80")
                   for url in urls]
    if authorities[0] in authorities[1:]:
        raise Refused("rustfs_origin_conflict", "RustFS requires a separate browser authority")
    peers = settings.get("OB_TRUSTED_PROXIES", "").split()
    if mode == "proxy" and not peers:
        raise Refused("proxy_trust_required", "set OB_TRUSTED_PROXIES to exact Platform Edge peer IPs")
    for peer in peers:
        try:
            network = ipaddress.ip_network(peer, strict=True)
            if network.num_addresses != 1:
                raise ValueError
        except ValueError as error:
            raise Refused("proxy_trust_invalid", "trust only exact proxy IPs or /32 and /128 host routes") from error


def compose_up(root: Path, env_file: Path, runner: Runner, s3: bool = False, proxy: bool = False) -> None:
    # Fifteen minutes includes cold image pulls; a timeout preserves cached layers for retry.
    result = runner([
        "docker", "compose", "--project-directory", str(root), "--env-file", str(env_file),
        "-f", str(root / "compose.yaml"),
        *(["-f", str(root / "compose.s3.yaml"), "--profile", "s3"] if s3 else []),
        *(["-f", str(root / "compose.proxy.yaml")] if proxy else []),
        "up", "--detach", "--wait", "--wait-timeout", "300",
    ], timeout=900)
    if result.returncode != 0:
        raise Refused("compose_up_failed", (result.stderr or result.stdout).strip()[-2000:])


class LocalHTTPSConnection(http.client.HTTPSConnection):
    def connect(self):
        # Dial loopback while verifying the certificate and sending SNI for the public host.
        sock = socket.create_connection(("127.0.0.1", self.port), timeout=self.timeout)
        try:
            self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
        except BaseException:
            sock.close()
            raise


def wait_ready(url: str, timeout: float = 120.0, host: str | None = None, ca_data: str | None = None) -> None:
    deadline = time.monotonic() + timeout
    last = ""
    while time.monotonic() < deadline:
        try:
            request = urllib.request.Request(url, headers={"Host": host} if host else {})
            if host and url.startswith("https://127.0.0.1:"):
                target = urllib.parse.urlsplit(url)
                options = {"context": ssl.create_default_context(cadata=ca_data)} if ca_data else {}
                connection = LocalHTTPSConnection(host, port=target.port, timeout=5, **options)
                try:
                    connection.request("GET", target.path, headers={"Host": host})
                    status = connection.getresponse().status
                finally:
                    connection.close()
            else:
                with urllib.request.urlopen(request, timeout=5) as response:
                    status = response.status
            if status == 200:
                return
            last = f"http {status}"
        except (urllib.error.URLError, OSError, http.client.HTTPException) as error:
            last = str(error)
        time.sleep(3)
    raise Refused("not_ready", f"{url}: {last}")


def record_bootstrap(state_dir, root, env_file, started, state):
    try:
        task_record(state_dir, root, env_file, started, state)
    except (OSError, Unavailable):
        print('Bootstrap status record unavailable; inspect status storage privately.', file=sys.stderr)


# Bound bootstrap commands without changing the shared runner used for bulk checkpoint I/O.
def bootstrap(argv: list[str], runner: Runner = partial(run, timeout=60)) -> int:
    parser = argparse.ArgumentParser(prog="bootstrap.py", description=__doc__.splitlines()[0])
    parser.add_argument("--env-file", default=".env")
    parser.add_argument("--template", default=".env.example")
    parser.add_argument("--render-only", action="store_true",
                        help="write the env file, start nothing")
    args = parser.parse_args(argv)
    started = now()
    root = Path(__file__).resolve().parent.parent
    env_file = (root / args.env_file).resolve()
    template = (root / args.template).resolve()
    compose = root / "compose.yaml"

    installation = env_file == (root / ".env").resolve()
    if shutil.which("docker") is None and (installation or not args.render_only):
        raise Refused("docker_missing", "install Docker with the Compose plugin")

    lock_path = env_file.with_name(env_file.name + ".lock")
    with open(lock_path, "w", encoding="utf-8") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as error:
            raise Refused("bootstrap_already_running", str(lock_path)) from error

        lines, present = read_env(env_file)
        # Compose lets the shell override the env file. A shell value that differs from
        # the saved one would run the stack with a secret the file does not record.
        conflicts = sorted(k for k in MANAGED if k in present and k in os.environ and os.environ[k] != present[k])
        if conflicts:
            raise Refused("shell_env_conflict", "unset in the shell or fix .env: " + ", ".join(conflicts))
        missing = MANAGED - set(present)
        settings = {
            m.group("key"): unquote(m.group("value"))
            for m in (ENV_LINE.match(line) for line in lines) if m
        }
        defaults = {
            m.group("key"): unquote(m.group("value"))
            for m in (ENV_LINE.match(line) for line in template.read_text().splitlines()) if m
        }
        settings = defaults | settings
        settings.update({key: value for key, value in os.environ.items()
                         if key.startswith("OB_") or key in ("COMPOSE_PROFILES", "COMPOSE_PROJECT_NAME")})
        access_config(settings)
        s3 = "s3" in settings.get("COMPOSE_PROFILES", "").split(",")
        proxy = settings["OB_ACCESS_MODE"] == "proxy"
        settings["COMPOSE_FILE"] = ":".join(["compose.yaml"] + (["compose.s3.yaml"] if s3 else []) + (["compose.proxy.yaml"] if proxy else []))
        if os.environ.get("COMPOSE_FILE") and os.environ["COMPOSE_FILE"] != settings["COMPOSE_FILE"]:
            raise Refused("compose_file_conflict", "unset COMPOSE_FILE; bootstrap selects the storage and access overrides")
        project = project_name(settings)
        prefix = settings.get("OB_VOLUME_PREFIX") or PROJECT
        state_dir = Path(settings.get("OB_STATE_DIR", "./data"))
        if not state_dir.is_absolute():
            state_dir = root / state_dir
        data_dir = state_dir / "installation"
        mode = "s3" if s3 else "filesystem"
        marker = data_dir / "storage-mode"
        if not args.render_only and marker.exists() and marker.read_text().strip() != mode:
            raise Refused("storage_migration_required", "storage mode differs from the installation; restore or migrate explicitly")

        # Scratch render-only stays offline. Installation bootstrap checks volumes
        # even when all secrets are present, before writing any installation state.
        existing = []
        if installation or not args.render_only:
            existing = installation_state(root, data_dir, runner, project, prefix)
            if not (data_dir / "storage-mode").exists() and any(item.startswith("volume ") for item in existing):
                raise Refused("storage_mode_unknown",
                              f"project volumes exist without {data_dir / 'storage-mode'}; verify the prior storage mode, "
                              "then record filesystem or s3 in that file (see docs/operations/backup.md)")

        if missing and existing:
            raise Refused(
                "existing_installation_missing_secrets",
                "restore the original .env before starting; found " + "; ".join(existing),
            )
        if missing:
            fresh = generate(missing)
            # A secret supplied in the shell on a fresh install is the operator's choice;
            # record it instead of generating a different one.
            fresh.update({k: os.environ[k] for k in missing if os.environ.get(k)})
            write_env(env_file, lines, template, fresh)
        # The host observer selects the saved env file without shell overrides.
        settings['COMPOSE_PROJECT_NAME'] = project
        saved_keys = (
            "COMPOSE_PROJECT_NAME", "OB_STATE_DIR", "OB_VOLUME_PREFIX",
            "OB_ACCESS_MODE", "OB_PUBLIC_DOMAIN", "OB_GRAFANA_HOST", "OB_SCHEME",
            "OB_BIND_HOST", "OB_HTTP_PORT", "OB_HTTPS_PORT", "OB_PUBLIC_PORT_SUFFIX",
            "OB_TRUSTED_PROXIES", "OB_OPERATOR_ALLOW", "OB_GRAFANA_URL",
            "OB_GRAFANA_URL_HOST", "OB_GRAFANA_AUTHORITY", "COMPOSE_FILE", "COMPOSE_PROFILES",
            "OB_RUSTFS_CONSOLE", "OB_RUSTFS_HOST", "OB_RUSTFS_URL",
            "OB_RUSTFS_URL_HOST", "OB_RUSTFS_AUTHORITY",
        )
        lines = env_file.read_text().splitlines()
        for key in saved_keys:
            found = False
            for index, line in enumerate(lines):
                match = ENV_LINE.match(line)
                if match and match.group("key") == key:
                    if unquote(match.group("value")) != settings[key]:
                        lines[index] = f"{key}={settings[key]}"
                    found = True
            if not found:
                lines.append(f"{key}={settings[key]}")
            if key in os.environ:
                os.environ[key] = settings[key]
        write_env(env_file, lines, template, {})
        scheme = settings.get("OB_SCHEME", "http")
        default_port = "443" if scheme == "https" else "80"
        port = settings.get("OB_HTTPS_PORT" if scheme == "https" else "OB_HTTP_PORT", default_port)
        if settings["OB_ACCESS_MODE"] != "proxy" and not settings.get("OB_PUBLIC_PORT_SUFFIX") and port != default_port:
            suffix = ":" + port
            lines = env_file.read_text().splitlines()
            lines = [line for line in lines if not (ENV_LINE.match(line) and ENV_LINE.match(line).group("key") == "OB_PUBLIC_PORT_SUFFIX")]
            write_env(env_file, lines, template, {"OB_PUBLIC_PORT_SUFFIX": suffix})
            settings["OB_PUBLIC_PORT_SUFFIX"] = suffix
            if "OB_PUBLIC_PORT_SUFFIX" in os.environ:
                os.environ["OB_PUBLIC_PORT_SUFFIX"] = suffix
            print(f"Derived OB_PUBLIC_PORT_SUFFIX={suffix}; saved to {env_file}", file=sys.stderr)
        alert_config(settings)
        if args.render_only:
            print(json.dumps({"env": str(env_file), "project": project, "generated": sorted(missing)}))
            return 0

        # Preserve ordinary state-root permissions before private status storage is made.
        state_dir.mkdir(parents=True, exist_ok=True)
        # Record only after env/access/storage validation. Abruptly terminated runs remain unknown.
        record_bootstrap(state_dir, root, env_file, started, 'unknown')
        try:
            # Profiles cannot replace another service's config mount. Record the matching
            # override so later plain docker compose commands use the same storage mode.
            data_dir.mkdir(parents=True, exist_ok=True)
            marker.write_text(mode + "\n")
            (state_dir / "textfile").mkdir(parents=True, exist_ok=True)
            backup_dir = Path(settings.get("OB_BACKUP_DIR", "./data/backups"))
            if not backup_dir.is_absolute():
                backup_dir = root / backup_dir
            backup_dir.mkdir(parents=True, exist_ok=True)
            resolved = runner(["docker", "compose", "--project-directory", str(root),
                               "--env-file", str(env_file), "-f", str(compose),
                               *(["-f", str(root / "compose.s3.yaml"), "--profile", "s3"] if s3 else []),
                               *(["-f", str(root / "compose.proxy.yaml")] if proxy else []),
                               "config", "--format", "json"])
            if resolved.returncode:
                raise Refused("compose_config_failed", "inspect Compose configuration privately")
            write_versions(root, compose, settings, services=json.loads(resolved.stdout)["services"])
            delivery = write_provisioning(root, state_dir, settings)

            ensure_network(runner, settings.get("OB_PLATFORM_NETWORK", NETWORK))
            ensure_volumes(runner, prefix, project, s3)
            compose_up(root, env_file, runner, s3, proxy)
            scheme = settings.get("OB_SCHEME", "http")
            domain = settings.get("OB_PUBLIC_DOMAIN", "localhost")
            origin = domain + settings.get("OB_PUBLIC_PORT_SUFFIX", "")
            for service in ("grafana", "loki", "tempo", "mimir", "alloy"):
                wait_ready(f"{local_origin(settings)}/health/{service}", host=domain)
            if settings["OB_ACCESS_MODE"] == "public":
                wait_ready(f"{local_origin(settings)}/login", host=settings["OB_GRAFANA_HOST"])
            if settings["OB_ACCESS_MODE"] == "local":
                certificate = runner(["docker", "compose", "--project-directory", str(root), "--env-file", str(env_file),
                                      "exec", "-T", "caddy", "cat", "/data/caddy/pki/authorities/local/root.crt"])
                if certificate.returncode:
                    raise Refused("local_ca_unavailable", "cannot read this installation's public CA certificate")
                for service in ("grafana", "loki", "tempo", "mimir", "alloy"):
                    wait_ready(f"{local_origin(settings, 'https')}/health/{service}", host=domain, ca_data=certificate.stdout)
            record_bootstrap(state_dir, root, env_file, started, 'healthy')
            try:
                initial = runner([sys.executable, str(root / 'scripts/status_observer.py'),
                                  '--checkout', str(root), '--env-file', str(env_file)], timeout=120)
                if initial.returncode:
                    print('Initial status observation failed; retry the observer privately.', file=sys.stderr)
            except (OSError, subprocess.SubprocessError):
                print('Initial status observation failed; retry the observer privately.', file=sys.stderr)
            print(json.dumps({
                "status": "degraded" if delivery == "placeholder" else "ready",
                "problems": ["alert_delivery_placeholder"] if delivery == "placeholder" else [],
                "console": f"{scheme}://{origin}/",
                "grafana": grafana_origin(settings) + "/",
                "grafanaLogin": "admin",
                "next": "Log in to Grafana with admin and OB_GRAFANA_ADMIN_PASSWORD from .env; open Stacks or Explore.",
            }))
            return 0
        except BaseException:
            record_bootstrap(state_dir, root, env_file, started, 'unavailable')
            raise


def main() -> int:
    try:
        return bootstrap(sys.argv[1:])
    except Refused as refused:
        print(json.dumps({"error": refused.code, "detail": refused.detail}), file=sys.stderr)
        return 3 if refused.code in ("not_ready", "compose_up_failed") else 1
    except subprocess.TimeoutExpired:
        print(json.dumps({"error": "docker_timeout", "detail": "Docker did not finish within the operation deadline; inspect installation state before retrying."}), file=sys.stderr)
        return 3
    except SystemExit as exit_:  # argparse
        return 2 if exit_.code not in (0, None) else 0


if __name__ == "__main__":
    raise SystemExit(main())
