#!/usr/bin/env python3
"""Bring the Observability Stack up from a clean checkout, or refuse with a reason.

Lock the env file, fill in
missing secrets, refuse to invent secrets over existing data, create the shared platform
network, start the stack, wait for readiness, print the next step. Exit codes: 0 ready,
1 refused (the JSON line on stderr names why), 2 bad usage, 3 the stack did not become
ready. Python 3.11+ standard library only.
"""

from __future__ import annotations

import argparse
import fcntl
import json
import http.client
import socket
import os
import re
import secrets
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

PROJECT = "observability-stack"
NETWORK = "platform"
VOLUMES = ("caddy-data", "caddy-config", "grafana-data", "alloy-data",
           "loki-data", "tempo-data", "mimir-data", "rustfs-data")

# Secrets the stack needs and how many random bytes each gets (hex encoded).
SECRETS: dict[str, int] = {
    "OB_GRAFANA_ADMIN_PASSWORD": 24,
    "OB_S3_ACCESS_KEY": 10,
    "OB_S3_SECRET_KEY": 24,
}
MANAGED = set(SECRETS)
IMAGE_LINE = re.compile(r"^\s+image:\s+(?P<ref>\S+)\s*$")
ENV_LINE = re.compile(r"^(?:export\s+)?(?P<key>[A-Z][A-Z0-9_]*)=(?P<value>.*)$")


class Refused(Exception):
    def __init__(self, code: str, detail: str = "") -> None:
        super().__init__(code)
        self.code = code
        self.detail = detail


Runner = Callable[[list[str]], subprocess.CompletedProcess[str]]


def run(argv: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(argv, text=True, capture_output=True, check=False)


def read_env(path: Path) -> tuple[list[str], dict[str, str]]:
    """Return the raw lines and the managed assignments. Unmanaged lines are kept verbatim."""
    if not path.exists():
        return [], {}
    lines = path.read_text(encoding="utf-8").splitlines()
    values: dict[str, str] = {}
    for line in lines:
        match = ENV_LINE.match(line)
        if not match:
            continue
        key, value = match.group("key"), match.group("value")
        if key in MANAGED:
            if key in values:
                raise Refused("env_repair_required", f"{key} is set twice in {path}")
            if not value or value.startswith(("'", '"')) or "${" in value:
                raise Refused("env_repair_required", f"{key} must be a plain value in {path}")
            values[key] = value
    return lines, values


def generate(missing: set[str]) -> dict[str, str]:
    fresh: dict[str, str] = {}
    for key in sorted(missing):
        fresh[key] = secrets.token_hex(SECRETS[key])
    return fresh


def write_env(path: Path, lines: list[str], template: Path, fresh: dict[str, str]) -> None:
    if not lines:
        lines = template.read_text(encoding="utf-8").splitlines()
        lines += ["", "# Generated by scripts/bootstrap.py. Keep this file private and backed up."]
    lines += [f"{key}={value}" for key, value in fresh.items()]
    tmp = path.with_name(path.name + ".tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    os.replace(tmp, path)
    os.chmod(path, 0o600)


def unquote(value: str) -> str:
    """Compose accepts 'x' and "x"; a bare value is used as is."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def project_name(settings: dict[str, str]) -> str:
    """Same precedence as Compose: shell environment, then the env file, then name:."""
    return os.environ.get("COMPOSE_PROJECT_NAME") or unquote(settings.get("COMPOSE_PROJECT_NAME", "")) or PROJECT


def installation_state(root: Path, data_dir: Path, runner: Runner, project: str = PROJECT, prefix: str | None = None) -> list[str]:
    """Every place an earlier installation of this project could have left data."""
    found: list[str] = []
    prefixes = (f"{project}_", f"{prefix or project}_")
    if data_dir.exists():
        if not os.access(data_dir, os.R_OK | os.X_OK):
            raise Refused("data_dir_unreadable", str(data_dir))
        if any(data_dir.iterdir()):
            found.append(f"data at {data_dir}")
    result = runner(["docker", "volume", "ls", "--format", "{{.Name}}"])
    if result.returncode != 0:
        raise Refused("docker_unavailable", result.stderr.strip())
    names = {name for name in result.stdout.split() if name.startswith(prefixes)}
    labelled = runner(["docker", "volume", "ls", "--filter",
                       f"label=com.docker.compose.project={project}", "--format", "{{.Name}}"])
    if labelled.returncode != 0:
        raise Refused("docker_unavailable", labelled.stderr.strip())
    for name in sorted(names | set(labelled.stdout.split())):
        found.append(f"volume {name}")
    return found


def images(compose: Path) -> dict[str, str]:
    """Service name to image tag, read from compose.yaml without a YAML parser."""
    out: dict[str, str] = {}
    service = ""
    for line in compose.read_text(encoding="utf-8").splitlines():
        head = re.match(r"^  (?P<name>[a-z][a-z0-9-]*):\s*$", line)
        if head:
            service = head.group("name")
        match = IMAGE_LINE.match(line)
        if match and service:
            ref = match.group("ref").split("@", 1)[0]
            out[service] = ref.rsplit(":", 1)[-1]
    return out


def write_versions(root: Path, compose: Path, settings: dict[str, str] | None = None) -> None:
    state = Path((settings or {}).get("OB_STATE_DIR", str(root / "data")))
    console = (state if state.is_absolute() else root / state) / "console"
    console.mkdir(parents=True, exist_ok=True)
    tags = images(compose)
    doc = {
        "pinnedAt": datetime.fromtimestamp(compose.stat().st_mtime, timezone.utc).isoformat(),
        "images": tags,
        "links": {
            "gateway": (settings or {}).get("OB_GATEWAY_URL", ""),
            "backplane": (settings or {}).get("OB_BACKPLANE_URL", ""),
        },
    }
    (console / "versions.json").write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")


def ensure_network(runner: Runner, name: str = NETWORK) -> None:
    probe = runner(["docker", "network", "inspect", name])
    if probe.returncode == 0:
        return
    created = runner(["docker", "network", "create", name])
    if created.returncode != 0:
        raise Refused("network_create_failed", created.stderr.strip())


def ensure_volumes(runner: Runner, prefix: str, project: str, s3: bool = False) -> None:
    for key in VOLUMES:
        if key == "rustfs-data" and not s3:
            continue
        name = f"{prefix}_{key}"
        result = runner(["docker", "volume", "create", "--label",
                         f"com.docker.compose.project={project}", name])
        if result.returncode:
            raise Refused("volume_create_failed", name)


def alert_config(settings: dict[str, str]) -> tuple[str, dict[str, str]]:
    if settings.get("OB_ALERT_WEBHOOK_URL"):
        url = urllib.parse.urlsplit(settings["OB_ALERT_WEBHOOK_URL"])
        if url.scheme not in ("http", "https") or not url.hostname:
            raise Refused("alert_delivery_invalid", "OB_ALERT_WEBHOOK_URL must be an HTTP(S) URL")
        return "webhook", {}
    if settings.get("OB_ALERT_EMAIL") and not settings["OB_ALERT_EMAIL"].endswith("@example.invalid") and settings.get("OB_SMTP_URL"):
        url = urllib.parse.urlsplit(settings["OB_SMTP_URL"])
        if url.scheme not in ("smtp", "smtps") or not url.hostname:
            raise Refused("alert_delivery_invalid", "OB_SMTP_URL must be smtp[s]://[user:password@]host:port")
        try:
            port = url.port or (465 if url.scheme == "smtps" else 587)
        except ValueError as error:
            raise Refused("alert_delivery_invalid", "invalid SMTP port") from error
        host = f"[{url.hostname}]" if ":" in url.hostname else url.hostname
        return "email", {
            "enabled": "true", "host": f"{host}:{port}",
            "user": urllib.parse.unquote(url.username or ""),
            "password": urllib.parse.unquote(url.password or ""),
            "from_address": settings["OB_ALERT_EMAIL"],
            "startTLS_policy": "MandatoryStartTLS" if url.scheme == "smtp" else "NoStartTLS",
        }
    if settings.get("OB_ALERTS") == "placeholder":
        return "placeholder", {}
    raise Refused("alert_delivery_required", "set OB_ALERT_WEBHOOK_URL or OB_ALERT_EMAIL and OB_SMTP_URL; "
                  "OB_ALERTS=placeholder explicitly permits degraded delivery")


def write_provisioning(root: Path, state: Path, settings: dict[str, str]) -> str:
    kind, smtp = alert_config(settings)
    state.mkdir(mode=0o700, parents=True, exist_ok=True)
    os.chmod(state, 0o700)
    provisioning = state / "grafana-provisioning"
    shutil.copytree(root / "docker/grafana/provisioning", provisioning, dirs_exist_ok=True)
    contact = {"apiVersion": 1, "contactPoints": [{"orgId": 1, "name": "configure-delivery",
               "receivers": [{"uid": "configure-delivery", "type": "email" if kind == "placeholder" else kind,
                              "disableResolveMessage": False, "settings":
                              {"url": "$OB_ALERT_WEBHOOK_URL"} if kind == "webhook" else
                              {"addresses": "$OB_ALERT_EMAIL" if kind == "email" else "configure@example.invalid"}}]}],
               "policies": [{"orgId": 1, "receiver": "configure-delivery", "group_by": ["grafana_folder", "alertname"]}]}
    (provisioning / "alerting/contact-points.yaml").write_text(json.dumps(contact, indent=2) + "\n")
    for value in smtp.values():
        if any(c in value for c in ('\n', '\r', '"""')):
            raise Refused("alert_delivery_invalid", "SMTP values must be single-line without triple quotes")
    (state / "grafana.ini").write_text("[smtp]\n" + "".join(f'{key} = """{value}"""\n' for key, value in smtp.items()))
    os.chmod(state / "grafana.ini", 0o644)
    console = state / "console"
    console.mkdir(parents=True, exist_ok=True)
    marker = console / "alerts-degraded.json"
    if kind == "placeholder":
        marker.write_text('{"status":"degraded","problem":"alert_delivery_placeholder"}\n')
    else:
        marker.unlink(missing_ok=True)
    return kind


def local_origin(settings: dict[str, str]) -> str:
    scheme = settings.get("OB_LISTEN_SCHEME") or settings.get("OB_SCHEME", "http")
    port = settings.get("OB_HTTPS_PORT" if scheme == "https" else "OB_HTTP_PORT") or ("443" if scheme == "https" else "80")
    return f"{scheme}://127.0.0.1:{port}"


def compose_up(root: Path, env_file: Path, runner: Runner, s3: bool = False) -> None:
    result = runner([
        "docker", "compose", "--project-directory", str(root), "--env-file", str(env_file),
        "-f", str(root / "compose.yaml"),
        *(["-f", str(root / "compose.s3.yaml"), "--profile", "s3"] if s3 else []),
        "up", "--detach", "--wait", "--wait-timeout", "300",
    ])
    if result.returncode != 0:
        raise Refused("compose_up_failed", (result.stderr or result.stdout).strip()[-2000:])


class LocalHTTPSConnection(http.client.HTTPSConnection):
    def connect(self):
        # Dial loopback while verifying the certificate and sending SNI for the public host.
        sock = socket.create_connection(("127.0.0.1", self.port), timeout=self.timeout)
        try:
            self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
        except BaseException:
            sock.close()
            raise


def wait_ready(url: str, timeout: float = 120.0, host: str | None = None) -> None:
    deadline = time.monotonic() + timeout
    last = ""
    while time.monotonic() < deadline:
        try:
            request = urllib.request.Request(url, headers={"Host": host} if host else {})
            if host and url.startswith("https://127.0.0.1:"):
                target = urllib.parse.urlsplit(url)
                connection = LocalHTTPSConnection(host, port=target.port, timeout=5)
                try:
                    connection.request("GET", target.path, headers={"Host": host})
                    status = connection.getresponse().status
                finally:
                    connection.close()
            else:
                with urllib.request.urlopen(request, timeout=5) as response:
                    status = response.status
            if status == 200:
                return
            last = f"http {status}"
        except (urllib.error.URLError, OSError, http.client.HTTPException) as error:
            last = str(error)
        time.sleep(3)
    raise Refused("not_ready", f"{url}: {last}")


def bootstrap(argv: list[str], runner: Runner = run) -> int:
    parser = argparse.ArgumentParser(prog="bootstrap.py", description=__doc__.splitlines()[0])
    parser.add_argument("--env-file", default=".env")
    parser.add_argument("--template", default=".env.example")
    parser.add_argument("--render-only", action="store_true",
                        help="write the env file, start nothing")
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parent.parent
    env_file = (root / args.env_file).resolve()
    template = (root / args.template).resolve()
    compose = root / "compose.yaml"

    installation = env_file == (root / ".env").resolve()
    if shutil.which("docker") is None and (installation or not args.render_only):
        raise Refused("docker_missing", "install Docker with the Compose plugin")

    lock_path = env_file.with_name(env_file.name + ".lock")
    with open(lock_path, "w", encoding="utf-8") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as error:
            raise Refused("bootstrap_already_running", str(lock_path)) from error

        lines, present = read_env(env_file)
        # Compose lets the shell override the env file. A shell value that differs from
        # the saved one would run the stack with a secret the file does not record.
        conflicts = sorted(k for k in MANAGED if k in present and k in os.environ and os.environ[k] != present[k])
        if conflicts:
            raise Refused("shell_env_conflict", "unset in the shell or fix .env: " + ", ".join(conflicts))
        missing = MANAGED - set(present)
        settings = {
            m.group("key"): unquote(m.group("value"))
            for m in (ENV_LINE.match(line) for line in lines) if m
        }
        defaults = {
            m.group("key"): unquote(m.group("value"))
            for m in (ENV_LINE.match(line) for line in template.read_text().splitlines()) if m
        }
        settings = defaults | settings
        settings.update({key: value for key, value in os.environ.items()
                         if key.startswith("OB_") or key in ("COMPOSE_PROFILES", "COMPOSE_PROJECT_NAME")})
        project = project_name(settings)
        prefix = settings.get("OB_VOLUME_PREFIX") or PROJECT
        state_dir = Path(settings.get("OB_STATE_DIR", "./data"))
        if not state_dir.is_absolute():
            state_dir = root / state_dir
        data_dir = state_dir / "installation"

        # Scratch render-only stays offline. Installation bootstrap checks volumes
        # even when all secrets are present, before writing any installation state.
        existing = []
        if installation or not args.render_only:
            existing = installation_state(root, data_dir, runner, project, prefix)
            if not (data_dir / "storage-mode").exists() and any(item.startswith("volume ") for item in existing):
                raise Refused("storage_mode_unknown",
                              f"project volumes exist without {data_dir / 'storage-mode'}; verify the prior storage mode, "
                              "then record filesystem or s3 in that file (see docs/operations/backup.md)")

        if missing and existing:
            raise Refused(
                "existing_installation_missing_secrets",
                "restore the original .env before starting; found " + "; ".join(existing),
            )
        if missing:
            fresh = generate(missing)
            # A secret supplied in the shell on a fresh install is the operator's choice;
            # record it instead of generating a different one.
            fresh.update({k: os.environ[k] for k in missing if os.environ.get(k)})
            write_env(env_file, lines, template, fresh)
        scheme = settings.get("OB_SCHEME", "http")
        default_port = "443" if scheme == "https" else "80"
        port = settings.get("OB_HTTPS_PORT" if scheme == "https" else "OB_HTTP_PORT", default_port)
        if (settings.get("OB_LISTEN_SCHEME") or scheme) == scheme and not settings.get("OB_PUBLIC_PORT_SUFFIX") and port != default_port:
            suffix = ":" + port
            lines = env_file.read_text().splitlines()
            lines = [line for line in lines if not (ENV_LINE.match(line) and ENV_LINE.match(line).group("key") == "OB_PUBLIC_PORT_SUFFIX")]
            write_env(env_file, lines, template, {"OB_PUBLIC_PORT_SUFFIX": suffix})
            settings["OB_PUBLIC_PORT_SUFFIX"] = suffix
            if "OB_PUBLIC_PORT_SUFFIX" in os.environ:
                os.environ["OB_PUBLIC_PORT_SUFFIX"] = suffix
            print(f"Derived OB_PUBLIC_PORT_SUFFIX={suffix}; saved to {env_file}", file=sys.stderr)
        alert_config(settings)
        if args.render_only:
            print(json.dumps({"env": str(env_file), "project": project, "generated": sorted(missing)}))
            return 0

        # Profiles cannot replace another service's config mount. Record the matching
        # override so later plain docker compose commands use the same storage mode.
        profiles = settings.get("COMPOSE_PROFILES", "").split(",")
        s3 = "s3" in profiles
        mode = "s3" if s3 else "filesystem"
        marker = data_dir / "storage-mode"
        if marker.exists() and marker.read_text().strip() != mode:
            raise Refused("storage_migration_required", "storage mode differs from the installation; restore or migrate explicitly")
        settings["COMPOSE_FILE"] = "compose.yaml:compose.s3.yaml" if s3 else "compose.yaml"
        # Preserve operator lines verbatim; only the selected Compose settings change.
        lines = env_file.read_text().splitlines()
        for key in ("COMPOSE_FILE", "COMPOSE_PROFILES"):
            found = False
            for index, line in enumerate(lines):
                match = ENV_LINE.match(line)
                if match and match.group("key") == key:
                    if unquote(match.group("value")) != settings[key]:
                        lines[index] = f"{key}={settings[key]}"
                    found = True
            if not found:
                lines.append(f"{key}={settings[key]}")
        write_env(env_file, lines, template, {})
        data_dir.mkdir(parents=True, exist_ok=True)
        marker.write_text(mode + "\n")
        (state_dir / "textfile").mkdir(parents=True, exist_ok=True)
        backup_dir = Path(settings.get("OB_BACKUP_DIR", "./data/backups"))
        if not backup_dir.is_absolute():
            backup_dir = root / backup_dir
        backup_dir.mkdir(parents=True, exist_ok=True)
        write_versions(root, compose, settings)
        delivery = write_provisioning(root, state_dir, settings)

        ensure_network(runner, settings.get("OB_PLATFORM_NETWORK", NETWORK))
        ensure_volumes(runner, prefix, project, s3)
        compose_up(root, env_file, runner, s3)
        scheme = settings.get("OB_SCHEME", "http")
        domain = settings.get("OB_PUBLIC_DOMAIN", "localhost")
        origin = domain + settings.get("OB_PUBLIC_PORT_SUFFIX", "")
        for service in ("grafana", "loki", "tempo", "mimir", "alloy"):
            wait_ready(f"{local_origin(settings)}/health/{service}", host=domain)
        print(json.dumps({
            "status": "degraded" if delivery == "placeholder" else "ready",
            "problems": ["alert_delivery_placeholder"] if delivery == "placeholder" else [],
            "console": f"{scheme}://{origin}/",
            "grafana": f"{scheme}://grafana.{origin}/",
            "grafanaLogin": "admin",
            "next": "Log in to Grafana with admin and OB_GRAFANA_ADMIN_PASSWORD from .env; open Stacks or Explore.",
        }))
        return 0


def main() -> int:
    try:
        return bootstrap(sys.argv[1:])
    except Refused as refused:
        print(json.dumps({"error": refused.code, "detail": refused.detail}), file=sys.stderr)
        return 3 if refused.code in ("not_ready", "compose_up_failed") else 1
    except SystemExit as exit_:  # argparse
        return 2 if exit_.code not in (0, None) else 0


if __name__ == "__main__":
    raise SystemExit(main())
