apiVersion: 1
prune: true
datasources:
  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    url: http://mimir:8080/prometheus
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Mimir
      timeInterval: 15s
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
